name: Add leg raises
description: Add a leg raises workout
title: Record leg raises
labels: workout

body:
  - type: input
    attributes:
      label: Date
      description: >
        When did the workout take place? (Format in a way GNU date can
        understand.)
      placeholder: YYYY-MM-DD
      value: today
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Style
      description: What progression level was this on?
      options:
        - Knee
        - Advanced knee
        - Alternating leg
        - Full leg
        - Tuck plow
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Set 1
      description: How many leg raises in set 1?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Set 2
      description: How many leg raises in set 2?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
    validations:
      required: true
