name: Add bridges

on:
  workflow_dispatch:
    inputs:
      date:
        description: Date
        required: true
        default: today
        type: string
      style:
        description: Style
        required: true
        type: choice
        default: Straight
        options:
          - Glute
          - Straight
          - Wall
          - Incline
          - Head
          - Full
          - Wheel
      set1:
        description: Set 1
        required: true
        type: string
      set2:
        description: Set 2
        required: true
        type: string
      set3:
        description: Set 3
        required: true
        type: string

jobs:
  entry:
    name: Add new bridges entry
    uses: ./.github/workflows/entry.yml
    with:
      exercise: bridges
      date: ${{ inputs.date }}
      style: ${{ inputs.style }}
      set1: ${{ fromJSON(format('{0}', inputs.set1)) }}
      set2: ${{ fromJSON(format('{0}', inputs.set2)) }}
      set3: ${{ fromJSON(format('{0}', inputs.set3)) }}
